import type {
  AgentRun,
  FileItem,
  FounderBoxState,
  Integration,
  MemoryItem,
  MigrationJob,
  PMDocument,
  Project,
  QAReport,
  ReportItem,
  User,
  Workspace
} from "@/types";

export const demoUser: User = {
  id: "user-demo-founder",
  name: "Aarav Founder",
  email: "aarav@founderbox.ai",
  avatarInitials: "AF"
};

export const demoWorkspace: Workspace = {
  id: "workspace-founderbox",
  name: "FounderBox Demo Workspace",
  defaultProjectId: "demo-phere",
  plan: "Free Demo"
};

export const sampleProjects: Project[] = [
  {
    id: "demo-phere",
    name: "Phere",
    description:
      "Indian wedding finance and planning PWA with vendor payments, family budgets, guest workflows, and shared decision memory.",
    type: "PWA",
    status: "active",
    createdAt: "2026-04-12T10:30:00.000Z",
    lastActivityAt: "2026-06-10T11:20:00.000Z",
    integrations: ["GitHub", "Google Drive"],
    agentRunCount: 18,
    memoryHealth: 86
  },
  {
    id: "demo-qaagent",
    name: "QaAgent",
    description:
      "AI QA automation framework for product teams that need repeatable smoke, regression, and UI quality reports.",
    type: "SaaS",
    status: "active",
    createdAt: "2026-03-22T08:10:00.000Z",
    lastActivityAt: "2026-06-09T15:45:00.000Z",
    integrations: ["GitHub", "Slack"],
    agentRunCount: 27,
    memoryHealth: 78
  },
  {
    id: "demo-zybra",
    name: "Zybra Migration",
    description:
      "Accounting and ERP data migration workspace for cleaning customer masters, opening balances, invoices, and stock data.",
    type: "Migration",
    status: "paused",
    createdAt: "2026-02-16T12:00:00.000Z",
    lastActivityAt: "2026-06-05T09:10:00.000Z",
    integrations: ["Google Drive"],
    agentRunCount: 12,
    memoryHealth: 71
  }
];

export const sampleMemories: MemoryItem[] = [
  {
    id: "mem-phere-1",
    projectId: "demo-phere",
    title: "Use family wallet as the first monetizable module",
    type: "Decision",
    content:
      "The first premium workflow for Phere will be a family wallet that tracks vendor advances, contribution commitments, and settlement reminders. Planning features stay free until the wallet proves repeat value.",
    tags: ["pricing", "mvp", "wallet"],
    source: "Manual Decision",
    createdAt: "2026-06-10T09:20:00.000Z"
  },
  {
    id: "mem-phere-2",
    projectId: "demo-phere",
    title: "Guest import needs sample template",
    type: "Bug",
    content:
      "QA run found that users cannot download a sample guest import template before uploading records. This blocks first-time setup for families using spreadsheets.",
    tags: ["qa", "import", "onboarding"],
    source: "QA Report #3",
    createdAt: "2026-06-09T14:40:00.000Z"
  },
  {
    id: "mem-phere-3",
    projectId: "demo-phere",
    title: "MVP timeline compressed to six weeks",
    type: "Document",
    content:
      "AI PM Agent generated a six-week MVP plan focused on vendor directory, budget tracker, guest import, family wallet, and event checklist.",
    tags: ["prd", "roadmap", "mvp"],
    source: "PRD generated by AI PM Agent",
    createdAt: "2026-06-08T07:55:00.000Z"
  },
  {
    id: "mem-qa-1",
    projectId: "demo-qaagent",
    title: "Browser automation remains backend phase work",
    type: "Decision",
    content:
      "QaAgent demo will simulate browser runs in the frontend. Real Playwright execution, credentials vault, screenshots, and job retries move to the backend phase.",
    tags: ["architecture", "qa", "backend"],
    source: "Manual Decision",
    createdAt: "2026-06-06T10:12:00.000Z"
  },
  {
    id: "mem-zybra-1",
    projectId: "demo-zybra",
    title: "GSTIN validation should not auto-correct legal identifiers",
    type: "Decision",
    content:
      "Migration Agent may suggest GSTIN fixes, but legal identifiers must remain user-approved before final export.",
    tags: ["migration", "compliance", "validation"],
    source: "Migration Job #2",
    createdAt: "2026-06-05T11:05:00.000Z"
  }
];

export const sampleAgentRuns: AgentRun[] = [
  {
    id: "run-1",
    projectId: "demo-phere",
    agent: "pm",
    title: "Generated Phere six-week MVP plan",
    status: "completed",
    createdAt: "2026-06-10T11:20:00.000Z",
    duration: "42 sec",
    summary: "Created modules, user stories, schema outline, risks, metrics, and sprint tasks."
  },
  {
    id: "run-2",
    projectId: "demo-phere",
    agent: "qa",
    title: "Functional QA run on onboarding",
    status: "completed",
    createdAt: "2026-06-09T14:40:00.000Z",
    duration: "1 min 18 sec",
    summary: "Found 6 frontend issues across login, imports, cards, validation, and exports."
  },
  {
    id: "run-3",
    projectId: "demo-zybra",
    agent: "migration",
    title: "Customer master mapping review",
    status: "completed",
    createdAt: "2026-06-05T09:10:00.000Z",
    duration: "54 sec",
    summary: "Suggested mappings for ledger name, mobile number, GSTIN, balance, email, and address."
  },
  {
    id: "run-4",
    projectId: "demo-qaagent",
    agent: "memory",
    title: "Searched run-history decisions",
    status: "completed",
    createdAt: "2026-06-07T16:25:00.000Z",
    duration: "8 sec",
    summary: "Returned three source-backed decisions about demo mode and backend job execution."
  }
];

export const samplePMDocuments: PMDocument[] = [
  {
    id: "pm-phere-1",
    projectId: "demo-phere",
    title: "Phere MVP Product Plan",
    idea: "Wedding planning PWA with family budgets and vendor payment memory.",
    createdAt: "2026-06-08T07:55:00.000Z",
    sections: [
      {
        title: "Product Summary",
        content:
          "Phere helps Indian families plan wedding work, control vendor spending, and keep important decisions visible across family members."
      },
      {
        title: "MVP Scope",
        content:
          "Vendor directory, budget tracker, guest import, family wallet, event checklist, and Founder Black Box style decision memory."
      },
      {
        title: "Success Metrics",
        content:
          "Activation through first budget created, vendor advance recorded, guest list imported, and two family members invited."
      }
    ]
  }
];

export const sampleQAReports: QAReport[] = [
  {
    id: "qa-phere-3",
    projectId: "demo-phere",
    title: "Phere Onboarding Functional QA",
    url: "https://demo.phere.app",
    reportType: "Functional",
    createdAt: "2026-06-09T14:40:00.000Z",
    summary:
      "Demo QA run completed with 6 issues. Highest impact areas are import templates, mobile field validation, and responsive dashboard cards.",
    steps: [
      "Opening website",
      "Checking login page",
      "Testing navigation",
      "Testing forms",
      "Checking validation",
      "Capturing screenshots",
      "Generating report"
    ],
    issues: [
      {
        id: "issue-1",
        module: "Leads",
        issue: "Mobile number field accepts alphabets",
        description:
          "The mobile number input allows non-numeric characters while creating a lead. This can result in invalid customer records.",
        priority: "High",
        status: "Open"
      },
      {
        id: "issue-2",
        module: "Login",
        issue: "Password error message is not clear",
        description:
          "When invalid credentials are entered, the system shows a generic error instead of explaining the issue.",
        priority: "Medium",
        status: "Open"
      },
      {
        id: "issue-3",
        module: "Dashboard",
        issue: "Cards overlap on mobile",
        description:
          "Summary cards break layout on small screens below 375px width.",
        priority: "Medium",
        status: "Open"
      },
      {
        id: "issue-4",
        module: "Import",
        issue: "Sample file format is missing",
        description:
          "User cannot download a sample import template before uploading records.",
        priority: "High",
        status: "Open"
      },
      {
        id: "issue-5",
        module: "Forms",
        issue: "Required field validation appears late",
        description:
          "Validation only appears after submitting instead of showing inline feedback.",
        priority: "Low",
        status: "Open"
      },
      {
        id: "issue-6",
        module: "Reports",
        issue: "Export button has no loading state",
        description: "User gets no feedback after clicking export.",
        priority: "Low",
        status: "Open"
      }
    ]
  }
];

export const sampleMigrationJobs: MigrationJob[] = [
  {
    id: "mig-zybra-2",
    projectId: "demo-zybra",
    title: "Customer Master Cleanup",
    dataType: "Customer Master",
    createdAt: "2026-06-05T09:10:00.000Z",
    status: "Ready",
    mappings: [
      {
        id: "map-1",
        targetField: "Ledger Name",
        suggestedSourceColumn: "Party Name",
        confidence: 96,
        required: true,
        action: "Use"
      },
      {
        id: "map-2",
        targetField: "Mobile Number",
        suggestedSourceColumn: "Mob",
        confidence: 88,
        required: false,
        action: "Review"
      },
      {
        id: "map-3",
        targetField: "GSTIN",
        suggestedSourceColumn: "GST No",
        confidence: 84,
        required: false,
        action: "Review"
      },
      {
        id: "map-4",
        targetField: "Opening Balance",
        suggestedSourceColumn: "Balance",
        confidence: 91,
        required: false,
        action: "Use"
      },
      {
        id: "map-5",
        targetField: "Balance Type",
        suggestedSourceColumn: "Auto Detect",
        confidence: 79,
        required: false,
        action: "Auto Detect"
      },
      {
        id: "map-6",
        targetField: "Email",
        suggestedSourceColumn: "Email",
        confidence: 94,
        required: false,
        action: "Use"
      },
      {
        id: "map-7",
        targetField: "Address",
        suggestedSourceColumn: "Address",
        confidence: 90,
        required: false,
        action: "Use"
      }
    ],
    validationErrors: [
      {
        id: "val-1",
        row: 4,
        field: "Mobile Number",
        issue: "Mobile number is not 10 digits",
        suggestedFix: "Remove country code and non-numeric characters",
        severity: "High"
      },
      {
        id: "val-2",
        row: 7,
        field: "GSTIN",
        issue: "GSTIN should be 15 characters",
        suggestedFix: "Ask finance owner to confirm legal GSTIN",
        severity: "Medium"
      }
    ],
    previewRows: [
      {
        "Ledger Name": "Ahuja Decorators",
        "Mobile Number": "9811122233",
        GSTIN: "07ABCDE1234F1Z5",
        "Opening Balance": 24000,
        "Balance Type": "Dr",
        Email: "accounts@ahuja.example",
        Address: "Delhi"
      },
      {
        "Ledger Name": "Mehta Caterers",
        "Mobile Number": "9988776655",
        GSTIN: "27ABCDE1234F1Z2",
        "Opening Balance": 17500,
        "Balance Type": "Cr",
        Email: "billing@mehta.example",
        Address: "Mumbai"
      }
    ]
  }
];

export const sampleFiles: FileItem[] = [
  {
    id: "file-1",
    projectId: "demo-phere",
    name: "Phere MVP Product Plan.md",
    fileType: "Markdown",
    sourceAgent: "AI PM Agent",
    createdAt: "2026-06-08T07:55:00.000Z",
    status: "ready"
  },
  {
    id: "file-2",
    projectId: "demo-phere",
    name: "Phere QA Functional Report.xlsx",
    fileType: "XLSX",
    sourceAgent: "AI QA Agent",
    createdAt: "2026-06-09T14:40:00.000Z",
    status: "ready"
  },
  {
    id: "file-3",
    projectId: "demo-zybra",
    name: "Customer Master Final Import.xlsx",
    fileType: "XLSX",
    sourceAgent: "AI Migration Agent",
    createdAt: "2026-06-05T09:10:00.000Z",
    status: "ready"
  }
];

export const sampleReports: ReportItem[] = [
  {
    id: "report-1",
    projectId: "demo-phere",
    title: "Phere MVP Product Plan",
    type: "PM Document",
    agent: "AI PM Agent",
    createdAt: "2026-06-08T07:55:00.000Z",
    status: "Ready",
    summary: "Execution-ready MVP plan with scope, schema, roadmap, sprint tasks, and risks."
  },
  {
    id: "report-2",
    projectId: "demo-phere",
    title: "Phere Onboarding Functional QA",
    type: "QA Report",
    agent: "AI QA Agent",
    createdAt: "2026-06-09T14:40:00.000Z",
    status: "Ready",
    summary: "Six issue report across onboarding, import, responsive layout, and export feedback."
  },
  {
    id: "report-3",
    projectId: "demo-zybra",
    title: "Customer Master Migration Summary",
    type: "Migration Report",
    agent: "AI Migration Agent",
    createdAt: "2026-06-05T09:10:00.000Z",
    status: "Ready",
    summary: "Mapped seven target fields and flagged high-risk mobile and GSTIN validation errors."
  },
  {
    id: "report-4",
    projectId: "demo-qaagent",
    title: "QaAgent Backend Phase Memory Summary",
    type: "Memory Summary",
    agent: "Founder Black Box",
    createdAt: "2026-06-07T16:25:00.000Z",
    status: "Ready",
    summary: "Decision summary for simulation boundaries, browser automation, and credential safety."
  }
];

export const sampleIntegrations: Integration[] = [
  {
    id: "github",
    name: "GitHub",
    status: "Demo / Not connected",
    description: "Connect repositories, commits, issues, and pull requests."
  },
  {
    id: "gmail",
    name: "Gmail",
    status: "Demo / Not connected",
    description: "Pull customer requests and founder conversations."
  },
  {
    id: "calendar",
    name: "Google Calendar",
    status: "Demo / Not connected",
    description: "Remember meetings and decisions."
  },
  {
    id: "drive",
    name: "Google Drive",
    status: "Demo / Not connected",
    description: "Index PRDs, docs, reports, and files."
  },
  {
    id: "notion",
    name: "Notion",
    status: "Coming soon",
    description: "Sync specs, project notes, and product docs."
  },
  {
    id: "slack",
    name: "Slack",
    status: "Coming soon",
    description: "Capture team decisions and customer escalation context."
  }
];

export const initialState: FounderBoxState = {
  user: demoUser,
  workspace: demoWorkspace,
  projects: sampleProjects,
  memories: sampleMemories,
  agentRuns: sampleAgentRuns,
  pmDocuments: samplePMDocuments,
  qaReports: sampleQAReports,
  migrationJobs: sampleMigrationJobs,
  files: sampleFiles,
  reports: sampleReports,
  integrations: sampleIntegrations
};
