"use client";

import { use, useMemo, useState } from "react";
import Link from "next/link";
import { Download, Eye, FileText, Filter } from "lucide-react";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog } from "@/components/ui/dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { Select } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { downloadText } from "@/lib/export";
import { useFounderBoxStore } from "@/lib/mock-store";
import { prettyDate } from "@/lib/utils";
import type { ReportItem } from "@/types";

export default function ReportsPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const store = useFounderBoxStore();
  const project = store.projects.find((item) => item.id === projectId);
  const [type, setType] = useState("all");
  const [agent, setAgent] = useState("all");
  const [date, setDate] = useState("all");
  const [selected, setSelected] = useState<ReportItem | null>(null);
  const [now] = useState(() => Date.now());

  const reports = useMemo(() => {
    return store.reports.filter((report) => {
      const matchesProject = report.projectId === projectId;
      const matchesType = type === "all" || report.type === type;
      const matchesAgent = agent === "all" || report.agent === agent;
      const age = now - new Date(report.createdAt).getTime();
      const matchesDate = date === "all" || (date === "30" && age <= 30 * 24 * 60 * 60 * 1000);
      return matchesProject && matchesType && matchesAgent && matchesDate;
    });
  }, [agent, date, now, projectId, store.reports, type]);

  if (!project) {
    return (
      <EmptyState
        icon={FileText}
        title="Project not found"
        description="Open a valid project to view reports."
        action={<Button asChild><Link href="/app/projects">Open projects</Link></Button>}
      />
    );
  }

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Reports"
        title={`${project.name} reports`}
        description="Generated PM documents, QA reports, migration reports, and memory summaries appear here after agent runs."
      />

      <Card className="p-4">
        <div className="grid gap-3 md:grid-cols-3">
          <Select value={type} onChange={(event) => setType(event.target.value)}>
            <option value="all">All report types</option>
            <option>PM Document</option>
            <option>QA Report</option>
            <option>Migration Report</option>
            <option>Memory Summary</option>
          </Select>
          <Select value={agent} onChange={(event) => setAgent(event.target.value)}>
            <option value="all">All agents</option>
            <option>AI PM Agent</option>
            <option>AI QA Agent</option>
            <option>AI Migration Agent</option>
            <option>Founder Black Box</option>
          </Select>
          <Select value={date} onChange={(event) => setDate(event.target.value)}>
            <option value="all">All dates</option>
            <option value="30">Last 30 days</option>
          </Select>
        </div>
      </Card>

      {reports.length ? (
        <div className="grid gap-4 xl:grid-cols-3">
          {reports.map((report) => (
            <Card key={report.id} interactive className="p-5">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <Badge variant="gold">{report.type}</Badge>
                  <h2 className="mt-3 text-lg font-semibold">{report.title}</h2>
                  <p className="mt-2 text-sm leading-6 text-muted">{report.summary}</p>
                </div>
                <StatusBadge value={report.status} />
              </div>
              <div className="mt-5 flex flex-wrap gap-2">
                <Badge>{report.agent}</Badge>
                <Badge>{project.name}</Badge>
                <Badge>{prettyDate(report.createdAt)}</Badge>
              </div>
              <div className="mt-5 flex gap-2">
                <Button variant="secondary" className="flex-1" onClick={() => setSelected(report)}>
                  <Eye className="h-4 w-4" />
                  View
                </Button>
                <Button variant="secondary" onClick={() => downloadText(`${report.title}.txt`, `${report.title}\n\n${report.summary}\n\nGenerated by ${report.agent}`)}>
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              </div>
            </Card>
          ))}
        </div>
      ) : (
        <EmptyState
          icon={Filter}
          title="No reports match"
          description="Change filters or run an agent to generate a new report."
        />
      )}

      <Dialog
        open={Boolean(selected)}
        onOpenChange={(open) => !open && setSelected(null)}
        title={selected?.title ?? "Report"}
        description={selected ? `${selected.type} generated by ${selected.agent}` : undefined}
      >
        {selected ? (
          <div className="space-y-4">
            <p className="text-sm leading-7 text-muted">{selected.summary}</p>
            <div className="flex flex-wrap gap-2">
              <StatusBadge value={selected.status} />
              <Badge variant="gold">{prettyDate(selected.createdAt)}</Badge>
              <Badge>{project.name}</Badge>
            </div>
          </div>
        ) : null}
      </Dialog>
    </div>
  );
}
