"use client";

import { use, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckSquare, Clipboard, Download, FileText, Save, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { copyText, downloadText, pmDocumentToMarkdown } from "@/lib/export";
import { generatePMDocument } from "@/lib/mock-agents";
import { useFounderBoxStore } from "@/lib/mock-store";
import { uid } from "@/lib/utils";
import type { PMDocument } from "@/types";

export default function PMAgentPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const store = useFounderBoxStore();
  const project = store.projects.find((item) => item.id === projectId);
  const [doc, setDoc] = useState<PMDocument | null>(null);
  const [form, setForm] = useState({
    productIdea: project?.description ?? "Founder workspace with project memory and specialized AI agents",
    targetUsers: "SaaS founders, agencies, product builders, and small teams",
    businessGoal: "Help teams turn scattered product context into execution-ready plans",
    timeline: "6 weeks",
    productType: "SaaS workspace",
    complexity: "Medium",
    useMemory: true
  });

  if (!project) {
    return (
      <EmptyState
        icon={Sparkles}
        title="Project not found"
        description="Open a valid project to generate a product plan."
        action={<Button asChild><Link href="/app/projects">Open projects</Link></Button>}
      />
    );
  }

  function generate() {
    const output = generatePMDocument({ projectId, ...form });
    setDoc(output);
    store.addAgentRun({
      id: uid("run"),
      projectId,
      agent: "pm",
      title: `Generated ${output.title}`,
      status: "completed",
      createdAt: new Date().toISOString(),
      duration: "38 sec",
      summary: "Generated product summary, scope, schema, roadmap, risks, and success metrics."
    });
    toast.success("Product plan generated in demo mode.");
  }

  function saveToMemory() {
    if (!doc) return;
    store.addPMDocument(doc);
    store.addMemory({
      projectId,
      title: doc.title,
      type: "Document",
      content: doc.sections.map((section) => `${section.title}: ${section.content}`).join("\n\n"),
      tags: ["prd", "pm-agent", "roadmap"],
      source: "PRD generated by AI PM Agent"
    });
    store.addReport({
      id: uid("report"),
      projectId,
      title: doc.title,
      type: "PM Document",
      agent: "AI PM Agent",
      createdAt: doc.createdAt,
      status: "Ready",
      summary: "Execution-ready product plan generated by the AI PM Agent demo workflow."
    });
    store.addFile({
      id: uid("file"),
      projectId,
      name: `${doc.title}.md`,
      fileType: "Markdown",
      sourceAgent: "AI PM Agent",
      createdAt: doc.createdAt,
      status: "ready"
    });
    toast.success("PM output saved to memory, reports, and files.");
  }

  function createChecklist() {
    if (!doc) return;
    store.addMemory({
      projectId,
      title: "QA checklist created from PM plan",
      type: "Note",
      content:
        "QA should cover onboarding, navigation, forms, validation, exports, responsive behavior, and report loading states from the generated PM plan.",
      tags: ["qa", "checklist", "pm-handoff"],
      source: "PRD generated by AI PM Agent"
    });
    toast.success("QA checklist saved to Founder Black Box.");
  }

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="AI PM Agent"
        title="Generate execution-ready product plans"
        description="Turn a product idea into summary, problem, MVP scope, feature modules, user stories, schema, API notes, roadmap, sprint tasks, risks, and success metrics."
      />

      <div className="grid gap-6 xl:grid-cols-[0.78fr_1fr]">
        <Card className="p-5">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-gold" />
            <h2 className="text-lg font-semibold">Plan inputs</h2>
          </div>
          <div className="mt-5 space-y-4">
            <Field label="Product idea">
              <Textarea value={form.productIdea} onChange={(event) => setForm({ ...form, productIdea: event.target.value })} />
            </Field>
            <Field label="Target users">
              <Input value={form.targetUsers} onChange={(event) => setForm({ ...form, targetUsers: event.target.value })} />
            </Field>
            <Field label="Business goal">
              <Input value={form.businessGoal} onChange={(event) => setForm({ ...form, businessGoal: event.target.value })} />
            </Field>
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="MVP timeline">
                <Input value={form.timeline} onChange={(event) => setForm({ ...form, timeline: event.target.value })} />
              </Field>
              <Field label="Product type">
                <Input value={form.productType} onChange={(event) => setForm({ ...form, productType: event.target.value })} />
              </Field>
            </div>
            <Field label="Complexity level">
              <Select value={form.complexity} onChange={(event) => setForm({ ...form, complexity: event.target.value })}>
                <option>Low</option>
                <option>Medium</option>
                <option>High</option>
              </Select>
            </Field>
            <label className="flex items-center gap-3 rounded-lg border border-border bg-surface2/52 p-3 text-sm text-muted">
              <input
                type="checkbox"
                checked={form.useMemory}
                onChange={(event) => setForm({ ...form, useMemory: event.target.checked })}
                className="h-4 w-4 accent-gold"
              />
              Use Founder Black Box memory
            </label>
            <Button className="w-full" size="lg" onClick={generate}>
              Generate Product Plan
              <Sparkles className="h-4 w-4" />
            </Button>
          </div>
        </Card>

        <div className="space-y-5">
          {doc ? (
            <>
              <Card className="p-5">
                <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
                  <div>
                    <Badge variant="gold">Generated in demo mode</Badge>
                    <h2 className="mt-3 text-2xl font-semibold">{doc.title}</h2>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Button variant="secondary" onClick={saveToMemory}><Save className="h-4 w-4" />Save</Button>
                    <Button variant="secondary" onClick={() => downloadText(`${doc.title}.md`, pmDocumentToMarkdown(doc), "text/markdown")}><Download className="h-4 w-4" />Markdown</Button>
                    <Button variant="secondary" onClick={() => copyText(pmDocumentToMarkdown(doc)).then(() => toast.success("Copied product plan."))}><Clipboard className="h-4 w-4" />Copy</Button>
                    <Button variant="secondary" onClick={createChecklist}><CheckSquare className="h-4 w-4" />QA checklist</Button>
                  </div>
                </div>
              </Card>
              <div className="grid gap-4">
                {doc.sections.map((section, index) => (
                  <Card key={section.title} className="p-5">
                    <div className="flex items-center gap-3">
                      <Badge variant="maroon">{String(index + 1).padStart(2, "0")}</Badge>
                      <h3 className="font-semibold">{section.title}</h3>
                    </div>
                    <p className="mt-3 text-sm leading-7 text-muted">{section.content}</p>
                  </Card>
                ))}
              </div>
            </>
          ) : (
            <EmptyState
              icon={FileText}
              title="No PM output yet"
              description="Fill the product inputs and generate a plan. The output can be saved to Founder Black Box, reports, and files."
              action={<Button onClick={generate}>Generate sample plan <ArrowRight className="h-4 w-4" /></Button>}
            />
          )}
        </div>
      </div>
    </div>
  );
}
